### ISSUE TITLE
Azure deployment is successful, but bot not responding.

### ISSUE THREAD

**Issue by scotwoodyard-csulb** [Azure-Samples/gen-ai-bot-in-a-box#13]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Deploy the solution to Azure by clicking on the "Deploy to Azure" button.  Go to the resource group and find the Azure Bot Services instance.  Select the Test in Web Chat option.  No welcome message is displayed, and no response to messages.

### Any log messages given by the failure
> I was unable to find any log messages.

### Expected/desired behavior
> Welcome message displayed, responses to messages

### OS and Version?
> Azure, .Net

### Versions
> 

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by MarcoABCardoso** [comment]
Hello @scotwoodyard-csulb!

This repository requires an application deployment after provisioning.
You may run it with the following command:
`azd deploy`

However, I believe the existance of the "Deploy to Azure" button was misleading in that sense. It has been removed, and users are encouraged to use the AZD CLI to deploy instead.

Thank you for reporting and please let us know if you have any further questions!
